### PR TITLE
Update cfs.py

### PR DESCRIPTION
**Pull request by aryan-1307**

### CODE REVIEW

**Comment by Sh0g0-1758** [comment]
@aryan-1307, why is the print statement commented out ?

**Comment by anant37289** [comment]
_6b41506d-dbca-43a2-8f7a-285c18841585

**Comment by Sh0g0-1758** [comment]
@anant37289, your thoughts ? 

I see you sent a photo of a lady magician, is that related to the project ?

**Comment by anant37289** [comment]
@Sh0g0-1758 , just a reference to wizard of oz. 
_We are not calculating the response time as a metric so it is commented out._

**Comment by Sh0g0-1758** [comment]
Ah I see, would it not make more sense to put it as a TODO ?

@anant37289 @aryan-1307

**Pull request merged**
